### ISSUE TITLE
Euphonium 1.21 crashes (Connector is not detected)

### ISSUE THREAD

**Issue by xXMolgadoGamer01Xx** [sleepingdragoninn/euphonium#2]
Hi.
So I downloaded this mod with Connector on 1.21 and the game crashes on start up saying that I need to install Connector even though it's intalled

Crash report: https://pastebin.com/VigW5sXc

Euphonium version 1.0.3

**Comment by sleepingdragoninn** [comment]
This is an issue with connector itself, and the crash message is misleading - try 1.21.1

**Comment by mpustovoi** [comment]
I still have that issue:
![Image](https://github.com/user-attachments/assets/eb2563e1-ad9b-49b8-b568-e5c057e030c0)
Forgified Fabric API is present too.

**Comment by HockeyZman2000** [comment]
Also having this same exact issue

**Comment by mpustovoi** [comment]
Forge, like NeoForge, is unable to identify the source of the problem on its own, so you need to use binary search to find the problematic mod.
Euphorium works well on a minimal setup, so it's definitely not the problem.
